### ISSUE TITLE
Missing license info

### ISSUE THREAD

**Issue by renatoi** [dequelabs/Deque-University-for-Android#24]
Hi,

First of all let me thank you for the awesome work done here.

I couldn't find the license info of this repo. It would be great if you could specify it, particularly in regards to the `a11yframework` present in the `app/src/main/java/com/dequesystems/` directory.

Thanks!

**Comment by dylanb** [comment]
The license is Mozilla Public License 2.0 https://www.mozilla.org/en-US/MPL/2.0/
