### ISSUE TITLE
[question] Deque University Android build error

### ISSUE THREAD

**Issue by khsbory** [dequelabs/Deque-University-for-Android#31]
Hello, I want to try to build this app as apk file and install to my android phone.
I installed Android Studio 2.3 with Dequeu master branch.
Once I open the project, below message is appeared.
    Error:Error:line (36)Could not get unknown property 'artifactory_username' for Credentials [username: null] of type org.gradle.api.internal.artifacts.repositories.DefaultPasswordCredentials_Decorated.
<a href="openFile:C:\Users\khsbo\OneDrive\documents\GitHub\Dequeu\Deque-University-for-Android\DequeU\build.gradle">Open File</a>

I don't know how to solve this problem.
Please help me.
Thank you.

**Comment by Prasildas-AHM** [comment]
Same here. Can you help with the username pass or can we register some place to get the credentials?
