### ISSUE TITLE
Can I get access to a trial version of the library for automation?

### ISSUE THREAD

**Issue by jorgepara** [dequelabs/Deque-University-for-Android#44]
I am interested in assessing Deque Attest for mobile apps. Specifically, how it can be integrated within a CI/CD pipeline for running accessibility tests automatically.

Already got the chance of doing it for iOS, with the trial version of the Attest framework; unfortunately, I do not find the way of doing the same for Android, although I have seen examples of the API for automation of these checks.

Is there any way I can get a trial version?

Thanks in advance.

**Comment by dylanb** [comment]
@jorgepara has this request been responded-to?

If not, please go to https://www.deque.com and submit a contact me
